use_frameworks!

platform :ios, '13.0'

target 'QRCodeSwiftScanner_Example' do
  pod 'QRCodeSwiftScanner', :path => '../../QRCodeSwiftScanner'

  target 'QRCodeSwiftScanner_Tests' do
    inherit! :search_paths

    
  end
end
