use_frameworks!

platform :ios, '10.0'

target 'QRCodeSwiftScanner_Example' do
  pod 'QRCodeSwiftScanner', :path => '../'

  target 'QRCodeSwiftScanner_Tests' do
    inherit! :search_paths

    
  end
end
